package bean;
// Generated 13/11/2023 10:03:16 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VeccPedidos generated by hbm2java
 */
@Entity
@Table(name="vecc_pedidos"
    ,catalog="db_victor_cardoso"
)
public class VeccPedidos  implements java.io.Serializable {


     private int idveccPedidos;
     private VeccCliente veccCliente;
     private int veccVendedor;
     private Date data;
     private Double veccTotal;

    public VeccPedidos() {
    }

	
    public VeccPedidos(int idveccPedidos, VeccCliente veccCliente, int veccVendedor) {
        this.idveccPedidos = idveccPedidos;
        this.veccCliente = veccCliente;
        this.veccVendedor = veccVendedor;
    }
    public VeccPedidos(int idveccPedidos, VeccCliente veccCliente, int veccVendedor, Date data, Double veccTotal) {
       this.idveccPedidos = idveccPedidos;
       this.veccCliente = veccCliente;
       this.veccVendedor = veccVendedor;
       this.data = data;
       this.veccTotal = veccTotal;
    }
   
     @Id 

    
    @Column(name="idvecc_pedidos", unique=true, nullable=false)
    public int getIdveccPedidos() {
        return this.idveccPedidos;
    }
    
    public void setIdveccPedidos(int idveccPedidos) {
        this.idveccPedidos = idveccPedidos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vecc_cliente", nullable=false)
    public VeccCliente getVeccCliente() {
        return this.veccCliente;
    }
    
    public void setVeccCliente(VeccCliente veccCliente) {
        this.veccCliente = veccCliente;
    }

    
    @Column(name="vecc_vendedor", nullable=false)
    public int getVeccVendedor() {
        return this.veccVendedor;
    }
    
    public void setVeccVendedor(int veccVendedor) {
        this.veccVendedor = veccVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data", length=10)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="vecc_total", precision=22, scale=0)
    public Double getVeccTotal() {
        return this.veccTotal;
    }
    
    public void setVeccTotal(Double veccTotal) {
        this.veccTotal = veccTotal;
    }




}


